spring:
  application:
    name: gateway
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  cloud:
    consul:
      #      host: http://18.191.238.30
      host: 18.191.238.30
      port: 8500
      enabled: true
      discovery:
        register: true
        instanceId: gateway_id_1
        serviceName: gateway
        hostname: 0.0.0.0
        port: 8888

server:
  address: 0.0.0.0
  port: 8888
  tomcat:
    uri-encoding: UTF-8

#zuul路由转发配置
zuul:
  routes:
    settlement_system:
      path: /settlement_system/**
      url: http://www.tichain.com.cn:3007/

myyml:
  routeAndRole:
  ################### 文件系统 ###########################
  - url: /file/**
    methods:
    - post
    - get
    roles:
    - ROOT
    - ADMIN
    - USER
  - url: /role/**
    methods:
    - get
    roles:
    - ADMIN
  - url: /**
    methods:
    - post
    roles:
    - USER
  ################### 文件系统 ###########################
#security:
#  oauth2:
#    sso:
#      loginPath: /login   # 登录路径
#    client:
#      clientId: aeaacc45cacdc0318b06
#      clientSecret: d883e6e713ab5715fa67b5aee9282edff41dc41f
#      accessTokenUri: https://github.com/login/oauth/access_token
#      userAuthorizationUri: https://github.com/login/oauth/authorize
#    resource:
#      userInfoUri: https://api.github.com/user
#      preferTokenInfo: false